# Migration Plan Workflow Configuration
name: migration-plan
description: "Document workflow that creates comprehensive, phased migration plans from current to target technology stack. Includes risk assessment, rollback strategies, testing approach, and timeline for safe, incremental transitions."
author: "Daniel"

# Paths
installed_path: "{project-root}/bmad/stack-advisor/workflows/migration-plan"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Critical variables from config
config_source: "{project-root}/bmad/stack-advisor/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Stack Advisor specific config
tech_currency_threshold: "{config_source}:tech_currency_threshold"
smb_scale_level: "{config_source}:smb_scale_level"

# Output
default_output_file: "{output_folder}/stack-advisor/migration-plan-{{date}}.md"

# Invocation control
standalone: true

# Recommended inputs (optional context)
recommended_inputs:
  - tech_selections: "{output_folder}/stack-advisor/tech-selections-*.md"
  - architecture_blueprint: "{output_folder}/stack-advisor/architecture-blueprint-*.md"
  - intake_results: "{output_folder}/stack-advisor/intake-session-*.md"
  - current_system_docs: "Any existing system documentation"

# Web bundle configuration
web_bundle:
  name: "migration-plan"
  description: "Document workflow that creates comprehensive, phased migration plans from current to target technology stack. Includes risk assessment, rollback strategies, testing approach, and timeline for safe, incremental transitions."
  author: "Daniel"
  instructions: "bmad/stack-advisor/workflows/migration-plan/instructions.md"
  validation: "bmad/stack-advisor/workflows/migration-plan/checklist.md"
  template: "bmad/stack-advisor/workflows/migration-plan/template.md"

  web_bundle_files:
    - "bmad/stack-advisor/workflows/migration-plan/instructions.md"
    - "bmad/stack-advisor/workflows/migration-plan/checklist.md"
    - "bmad/stack-advisor/workflows/migration-plan/template.md"
