# Generate Style Guide Workflow Configuration v2
# Multi-agent generation → Single file output
name: "generate-style-guide"
description: "Generate comprehensive design style guide using 5 specialist agents with feedback loop"
author: "Style Guide Forge"
version: "2.0.0"

# Critical variables from config
config_source: "{project-root}/bmad/style-guide-forge/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Module-specific config variables
style_guide_output_folder: "{config_source}:style_guide_output_folder"
screenshot_viewports: "{config_source}:screenshot_viewports"
typography_base_size: "{config_source}:typography_base_size"
typography_scale_ratio: "{config_source}:typography_scale_ratio"
spacing_base_unit: "{config_source}:spacing_base_unit"
max_feedback_rounds: "{config_source}:max_feedback_rounds"

# Module path and component files
installed_path: "{project-root}/bmad/style-guide-forge/workflows/generate-style-guide"
template: false
instructions: "{installed_path}/instructions.md"
checklist: "{installed_path}/checklist.md"

# Reference data files
typography_data: "{project-root}/bmad/style-guide-forge/data/typography-best-practices.md"
spacing_data: "{project-root}/bmad/style-guide-forge/data/spacing-systems.md"
component_data: "{project-root}/bmad/style-guide-forge/data/component-patterns.md"
accessibility_data: "{project-root}/bmad/style-guide-forge/data/accessibility-checklist.md"
motion_data: "{project-root}/bmad/style-guide-forge/data/motion-guidelines.md"

# Output - Single file
output_file: "{style_guide_output_folder}/style-guide.md"

# Screenshots folder (for reference analysis)
screenshots_folder: "{style_guide_output_folder}/reference-screenshots"

standalone: true

# Web bundle configuration
web_bundle:
  workflow: "bmad/style-guide-forge/workflows/generate-style-guide/workflow.yaml"
  files:
    - "bmad/style-guide-forge/workflows/generate-style-guide/workflow.yaml"
    - "bmad/style-guide-forge/workflows/generate-style-guide/instructions.md"
    - "bmad/style-guide-forge/workflows/generate-style-guide/checklist.md"
    - "bmad/style-guide-forge/data/typography-best-practices.md"
    - "bmad/style-guide-forge/data/spacing-systems.md"
    - "bmad/style-guide-forge/data/component-patterns.md"
    - "bmad/style-guide-forge/data/accessibility-checklist.md"
    - "bmad/style-guide-forge/data/motion-guidelines.md"
  existing_workflows: []

# Architecture note
# v2 changes:
# - 5 specialists work in parallel (removed scorer agent)
# - Director reviews each section with feedback loop (max 3 rounds)
# - All sections compiled into ONE file: style-guide.md
# - NO code exports (handled by design-system-forge)
