name: generate-palette
description: Generate a comprehensive, accessible color palette for a brand
version: "1.0"
category: design

entry_agent: color-palette-architect

inputs:
  required:
    - brand_personality
  optional:
    - industry
    - primary_color
    - color_temperature
    - palette_style
    - brand_guide_path

outputs:
  - color-palette.md
  - palette-data.json
  - palette-preview.html
  - accessibility-report.md
  - quality-scores.json

agents:
  - color-palette-architect
  - color-theorist
  - color-psychologist
  - accessibility-checker
  - palette-scorer

phases:
  - name: context
    description: Gather brand and preference context
    agent: color-palette-architect

  - name: theory
    description: Generate base palette using color theory
    agent: color-theorist

  - name: psychology
    description: Apply color psychology for semantic mapping
    agent: color-psychologist

  - name: accessibility
    description: Validate WCAG compliance
    agent: accessibility-checker

  - name: scoring
    description: Evaluate palette quality
    agent: palette-scorer

  - name: delivery
    description: Compile and deliver final outputs
    agent: color-palette-architect

quality_gates:
  harmony_score: 80
  accessibility_score: 90
  psychology_score: 75
  overall_score: 80
