# Blueprint Architect Workflow Configuration
name: blueprint-architect
description: "Document workflow that designs comprehensive system architecture including component design, data flow, deployment architecture, and visual diagrams. Creates professional architecture documentation ready for development."
author: "Daniel"

# Paths
installed_path: "{project-root}/bmad/stack-advisor/workflows/blueprint-architect"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Critical variables from config
config_source: "{project-root}/bmad/stack-advisor/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Stack Advisor specific config
smb_scale_level: "{config_source}:smb_scale_level"

# Output
default_output_file: "{output_folder}/stack-advisor/architecture-blueprint-{{date}}.md"

# Invocation control
standalone: true

# Recommended inputs (optional context)
recommended_inputs:
  - tech_selections: "{output_folder}/stack-advisor/tech-selections-*.md"
  - intake_results: "{output_folder}/stack-advisor/intake-session-*.md"
  - requirements_doc: "Any PRD, requirements, or business documentation"

# Scout's knowledge base (for tech reference)
scout_knowledge_base: "{project-root}/bmad/stack-advisor/agents/tech-research-sidecar/knowledge"

# Web bundle configuration
web_bundle:
  name: "blueprint-architect"
  description: "Document workflow that designs comprehensive system architecture including component design, data flow, deployment architecture, and visual diagrams. Creates professional architecture documentation ready for development."
  author: "Daniel"
  instructions: "bmad/stack-advisor/workflows/blueprint-architect/instructions.md"
  validation: "bmad/stack-advisor/workflows/blueprint-architect/checklist.md"
  template: "bmad/stack-advisor/workflows/blueprint-architect/template.md"

  web_bundle_files:
    - "bmad/stack-advisor/workflows/blueprint-architect/instructions.md"
    - "bmad/stack-advisor/workflows/blueprint-architect/checklist.md"
    - "bmad/stack-advisor/workflows/blueprint-architect/template.md"
