# Personal Content Audit Workflow
# Analyze user's past Instagram Reel performance
name: personal-content-audit
description: "Analyze your past Instagram Reel performance patterns to identify what works and optimize future content"
author: "Daniel"

# Paths
installed_path: "{project-root}/bmad/viral-reels-forge/workflows/personal-content-audit"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Critical variables from config
config_source: "{project-root}/bmad/viral-reels-forge/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
instagram_handle: "{config_source}:instagram_handle"
date: system-generated

# Data freshness rules
user_data_max_age_days: "{config_source}:user_data_max_age_days"

# Output configuration
default_output_file: "{output_folder}/content-audit-{{instagram_handle}}-{{date}}.md"

# Invocation control
standalone: true

# Web bundle configuration
web_bundle:
  name: "personal-content-audit"
  version: "1.0.0"
  web_bundle_files:
    - "bmad/viral-reels-forge/workflows/personal-content-audit/instructions.md"
    - "bmad/viral-reels-forge/workflows/personal-content-audit/template.md"
    - "bmad/viral-reels-forge/workflows/personal-content-audit/checklist.md"
