# Generate Voice Documentation Workflow v2
# Multi-agent generation with feedback loop → single file output

workflow:
  name: "Generate Voice Documentation"
  version: "2.0.0"
  module: voice-forge
  description: |
    Creates comprehensive brand voice documentation using 5 specialist agents
    working in parallel, with Director review and feedback loop, compiled into
    a single actionable voice-guide.md file.

    Architecture: Multi-agent depth + Single-file simplicity

trigger:
  command: "*generate"
  agent: voice-director

inputs:
  required:
    - name: reference_urls
      type: array
      description: "3-5 URLs of websites/social media with desired voice style"
      min_items: 3
      max_items: 5

    - name: brand_name
      type: string
      description: "The name of your brand"

  optional:
    - name: industry
      type: string
      default: "Technology"

    - name: target_audience
      type: string
      default: "General business audience"

    - name: brand_personality
      type: array
      description: "3-5 adjectives describing desired personality"

    - name: persona_name
      type: string
      description: "Name of brand avatar/ideal customer"

    - name: persona_gender
      type: string
      description: "Gender for consistent copy (feminine/masculine)"
      default: "feminine"

    - name: avoid
      type: array
      description: "Voice styles or tones to avoid"

outputs:
  primary:
    - voice-guide.md

  # No JSON files - all content compiled into single markdown

agents:
  orchestrator: voice-director

  specialists:
    - name: voice-identity-architect
      sections: ["Voice Snapshot", "Voice Dimensions"]
      focus: "WHO the brand is"

    - name: tone-strategist
      sections: ["Golden Rules"]
      focus: "Core principles that define the voice"

    - name: lexicon-curator
      sections: ["Say This/Not That", "Red Lines"]
      focus: "Word choices and prohibitions"

    - name: channel-specialist
      sections: ["Channel Quick Reference"]
      focus: "Platform-specific adaptations"

    - name: content-exemplar
      sections: ["Do/Don't", "Before/After Examples"]
      focus: "Show voice in action"

steps:
  - step: 1
    name: "Gather Inputs"
    action: prompt_user
    prompt: |
      Quick inputs for your voice guide:

      1. **Brand Name**
      2. **3-5 Reference URLs** (brands with voices you admire)
      3. **Target Audience**
      4. **3-5 Personality Words**
      5. **Persona Name** (e.g., "Carolina")
      6. **Persona Gender** (for consistent copy)
      7. **What to AVOID**

  - step: 2
    name: "Analyze References"
    action: webfetch_analysis
    tool: WebFetch
    foreach: reference_urls
    extract:
      - tone_patterns
      - vocabulary
      - personality_evidence
      - notable_phrases
    output: voice_dna_summary  # In memory, not file

  - step: 3
    name: "Load Reference Data"
    action: read_files
    files:
      - data/voice-dimensions.md
      - data/brand-archetypes.md
      - data/copywriter-standards.md

  - step: 4
    name: "Spawn 5 Specialists in Parallel"
    action: spawn_parallel
    critical: "All 5 Task calls MUST be in ONE message"
    agents:
      - voice-identity-architect
      - tone-strategist
      - lexicon-curator
      - channel-specialist
      - content-exemplar
    input_to_all:
      - voice_dna_summary
      - brand_context
      - copywriter_standards
    output: markdown_sections  # Each returns markdown

  - step: 5
    name: "Wait for Specialists"
    action: wait_all
    timeout: 300000

  - step: 6
    name: "Review & Feedback Loop"
    action: review_sections
    criteria:
      - brand_specific_not_generic
      - concrete_examples_included
      - actionable_for_copywriters
      - complies_with_copywriter_standards
      - consistent_across_sections
    feedback_loop:
      max_rounds: 3
      on_weak_section: |
        Send targeted feedback to specialist:
        - ISSUE: [specific problem]
        - EXAMPLE: [what's wrong]
        - FIX: [how to fix]
        Specialist regenerates with guidance.

  - step: 7
    name: "Compile Final Document"
    action: compile_document
    template: templates/voice-guide.md
    sections_order:
      - voice_snapshot
      - voice_dimensions
      - golden_rules
      - do_dont
      - say_this_not_that
      - before_after_examples
      - channel_quick_reference
      - red_lines
      - quick_check
    output: voice-guide.md

  - step: 8
    name: "Present Results"
    action: display_results
    format: |
      ✅ Voice Guide Generated!

      **Architecture Used:**
      - 5 specialist agents worked in parallel
      - Director reviewed and refined each section
      - Compiled into single actionable file

      **File:** voice-guide.md (~3-4 pages)
      **Location:** {output_folder}/

      **Sections:**
      1. Voice Snapshot - who you are
      2. Voice Dimensions - position on 4 scales
      3. Golden Rules - 5 core principles
      4. Do/Don't - quick reference
      5. Say This/Not That - vocabulary
      6. Before/After - learn by example
      7. Channel Reference - adapt by platform
      8. Red Lines - never do this

      Multi-agent quality. Single-file simplicity.

error_handling:
  webfetch_failure:
    action: "Skip URL, warn user, continue if 3+ URLs remain"

  specialist_timeout:
    action: "Retry once, then proceed with available sections"

  feedback_loop_exhausted:
    action: "Use best available version, note in output"
