# Cost Analysis Workflow Configuration
name: cost-analysis
description: "Comprehensive cost analysis for technology stack including TCO, break-even analysis, scaling projections, and cost optimization recommendations."
author: "Daniel"

# Paths
installed_path: "{project-root}/bmad/stack-advisor/workflows/cost-analysis"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Critical variables from config
config_source: "{project-root}/bmad/stack-advisor/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Stack Advisor specific config
tech_currency_threshold: "{config_source}:tech_currency_threshold"
smb_scale_level: "{config_source}:smb_scale_level"

# Output
default_output_file: "{output_folder}/stack-advisor/cost-analysis-{{date}}.md"

# Invocation control
standalone: true

# Recommended inputs (optional context)
recommended_inputs:
  - tech_selections: "{output_folder}/stack-advisor/tech-selections-*.md"
  - architecture_blueprint: "{output_folder}/stack-advisor/architecture-blueprint-*.md"
  - intake_results: "{output_folder}/stack-advisor/intake-session-*.md"

# Web bundle configuration
web_bundle:
  name: "cost-analysis"
  description: "Comprehensive cost analysis for technology stack including TCO, break-even analysis, scaling projections, and cost optimization recommendations."
  author: "Daniel"
  instructions: "bmad/stack-advisor/workflows/cost-analysis/instructions.md"
  validation: "bmad/stack-advisor/workflows/cost-analysis/checklist.md"
  template: "bmad/stack-advisor/workflows/cost-analysis/template.md"

  web_bundle_files:
    - "bmad/stack-advisor/workflows/cost-analysis/instructions.md"
    - "bmad/stack-advisor/workflows/cost-analysis/checklist.md"
    - "bmad/stack-advisor/workflows/cost-analysis/template.md"
