# Create Design System Workflow Configuration
name: "create-design-system"
description: "Full pipeline to create a comprehensive design system from brand inputs"
author: "Design System Forge"
version: "1.0.0"

# Critical variables from config
config_source: "{project-root}/bmad/design-system-forge/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Module-specific config variables
design_system_name: "{config_source}:design_system_name"
tech_stack: "{config_source}:tech_stack"
component_scope: "{config_source}:component_scope"
output_folder: "{config_source}:output_folder"
lightweight_mode: "{config_source}:lightweight_mode"
essential_components: "{config_source}:essential_components"

# Input file paths
brand_guide_path: "{config_source}:brand_guide_path"
style_guide_path: "{config_source}:style_guide_path"
color_palette_path: "{config_source}:color_palette_path"
references_path: "{config_source}:references_path"
logo_path: "{config_source}:logo_path"

# Module path and component files
installed_path: "{project-root}/bmad/design-system-forge/workflows/create-design-system"
template: false
instructions: "{installed_path}/instructions.md"

# Output paths
design_system_output: "{output_folder}/design-system"
tokens_output: "{design_system_output}/tokens"
components_output: "{design_system_output}/components"
docs_output: "{design_system_output}/docs"

standalone: true

# Web bundle configuration
web_bundle:
  workflow: "bmad/design-system-forge/workflows/create-design-system/workflow.yaml"
  files:
    - "bmad/design-system-forge/workflows/create-design-system/workflow.yaml"
    - "bmad/design-system-forge/workflows/create-design-system/instructions.md"
  existing_workflows: []
