# Create Design System Workflow Configuration v2
# Multi-agent generation → Code exports + Single doc
name: "create-design-system"
description: "Create design system using 3 specialist agents with feedback loop"
author: "Design System Forge"
version: "2.0.0"

# Critical variables from config
config_source: "{project-root}/bmad/design-system-forge/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Module-specific config variables
design_system_name: "{config_source}:design_system_name"
output_folder: "{config_source}:output_folder"
max_feedback_rounds: "{config_source}:max_feedback_rounds"

# Input file paths
style_guide_path: "{config_source}:style_guide_path"
color_palette_path: "{config_source}:color_palette_path"

# Module path and component files
installed_path: "{project-root}/bmad/design-system-forge/workflows/create-design-system"
template: false
instructions: "{installed_path}/instructions.md"

# Output - Single folder with 3 files
output_path: "{output_folder}/design-system"
output_files:
  tokens_css: "{output_path}/tokens.css"
  tokens_json: "{output_path}/tokens.json"
  documentation: "{output_path}/design-system.md"

standalone: true

# Web bundle configuration
web_bundle:
  workflow: "bmad/design-system-forge/workflows/create-design-system/workflow.yaml"
  files:
    - "bmad/design-system-forge/workflows/create-design-system/workflow.yaml"
    - "bmad/design-system-forge/workflows/create-design-system/instructions.md"
    - "bmad/design-system-forge/data/wcag-standards.md"
  existing_workflows: []

# Architecture note
# v2 changes:
# - 3 specialists work in parallel (removed documentation-writer)
# - Director reviews each output with feedback loop (max 3 rounds)
# - Output: tokens.css, tokens.json, design-system.md
# - Removed: individual component specs, multiple doc files
