# Competitor Deep Dive Workflow
# Intensive competitor intelligence for Instagram Reels
name: competitor-deep-dive
description: "Deep dive competitor intelligence analyzing Instagram Reels performance, formats, and content gaps"
author: "Daniel"

# Paths
installed_path: "{project-root}/bmad/viral-reels-forge/workflows/competitor-deep-dive"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Critical variables from config
config_source: "{project-root}/bmad/viral-reels-forge/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Data freshness rules
competitor_data_max_age_days: "{config_source}:competitor_data_max_age_days"

# Output configuration
default_output_file: "{output_folder}/competitor-analysis-{{date}}.md"

# Invocation control
standalone: true

# Web bundle configuration
web_bundle:
  name: "competitor-deep-dive"
  version: "1.0.0"
  web_bundle_files:
    - "bmad/viral-reels-forge/workflows/competitor-deep-dive/instructions.md"
    - "bmad/viral-reels-forge/workflows/competitor-deep-dive/template.md"
    - "bmad/viral-reels-forge/workflows/competitor-deep-dive/checklist.md"
