# Executive Summary Workflow Configuration
name: executive-summary
description: "Generate high-level executive summary from technical documentation. Perfect for stakeholders who need key decisions and rationale without technical depth."
author: "Daniel"

# Paths
installed_path: "{project-root}/bmad/stack-advisor/workflows/executive-summary"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Critical variables from config
config_source: "{project-root}/bmad/stack-advisor/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Stack Advisor specific config
smb_scale_level: "{config_source}:smb_scale_level"

# Output
default_output_file: "{output_folder}/stack-advisor/executive-summary-{{date}}.md"

# Invocation control
standalone: true

# Recommended inputs (load existing documentation)
recommended_inputs:
  - tech_spec: "{output_folder}/stack-advisor/tech-stack-specification-*.md"
  - architecture_blueprint: "{output_folder}/stack-advisor/architecture-blueprint-*.md"
  - comparison_matrix: "{output_folder}/stack-advisor/comparison-matrix-*.md"
  - cost_analysis: "{output_folder}/stack-advisor/cost-analysis-*.md"
  - intake_results: "{output_folder}/stack-advisor/intake-session-*.md"

# Web bundle configuration
web_bundle:
  name: "executive-summary"
  description: "Generate high-level executive summary from technical documentation. Perfect for stakeholders who need key decisions and rationale without technical depth."
  author: "Daniel"
  instructions: "bmad/stack-advisor/workflows/executive-summary/instructions.md"
  validation: "bmad/stack-advisor/workflows/executive-summary/checklist.md"
  template: "bmad/stack-advisor/workflows/executive-summary/template.md"

  web_bundle_files:
    - "bmad/stack-advisor/workflows/executive-summary/instructions.md"
    - "bmad/stack-advisor/workflows/executive-summary/checklist.md"
    - "bmad/stack-advisor/workflows/executive-summary/template.md"
