# Update Persona Workflow Configuration
name: update-persona
description: "Update existing personas with new market research or real qualification call data for continuous improvement"
author: "Persona Forge"

# Critical variables load from module config
config_source: "{project-root}/bmad/persona-forge/config.yaml"
output_folder: "{config_source}:output_folder"
persona_output_folder: "{config_source}:persona_output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"

# System variables
date: system-generated

# Agent references
market_intelligence_analyst: "{project-root}/bmad/persona-forge/agents/market-intelligence-analyst.md"
senior_persona_specialist: "{project-root}/bmad/persona-forge/agents/senior-persona-specialist.md"

# Module path and component files
installed_path: "{project-root}/bmad/persona-forge/workflows/update-persona"
template: false
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Output configuration
updated_output_file: "{persona_output_folder}/persona-{{persona_name_slug}}-v{{new_version}}-{{date}}.md"

# Update tracking
update_type: "" # "market_research" or "qualification_data" or "general_refresh"
previous_version: ""
new_version: ""

standalone: true

web_bundle:
  name: "update-persona"
  description: "Update existing personas with new market research or real qualification call data"
  author: "Persona Forge"
  instructions: "bmad/persona-forge/workflows/update-persona/instructions.md"
  web_bundle_files:
    - bmad/persona-forge/workflows/update-persona/instructions.md
    - bmad/persona-forge/workflows/update-persona/checklist.md
    - bmad/persona-forge/agents/market-intelligence-analyst.md
    - bmad/persona-forge/agents/senior-persona-specialist.md
