/**
 * Seja Livre / Jucana Mentoria - Tailwind CSS Configuration
 * Generated by Style Guide Forge
 *
 * Brand: Seja Livre - Empreenda com Leveza
 * Symbol: Dandelion (Dente-de-leao) - freedom and transformation
 * Voice: Libertadora (60%) + Mentora Sabia (40%)
 */

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      /* ============================================
         TYPOGRAPHY - Font Families
         ============================================ */
      fontFamily: {
        primary: ["'Lora'", 'Georgia', 'Cambria', "'Times New Roman'", 'serif'],
        secondary: ["'Century Gothic'", 'Century', "'URW Gothic'", "'Helvetica Neue'", 'Arial', 'sans-serif'],
        mono: ["'JetBrains Mono'", "'Fira Code'", "'SF Mono'", 'Monaco', 'Consolas', 'monospace'],
        // Aliases for convenience
        serif: ["'Lora'", 'Georgia', 'serif'],
        sans: ["'Century Gothic'", 'Century', 'sans-serif'],
      },

      /* ============================================
         TYPOGRAPHY - Font Sizes (Major Third 1.25)
         ============================================ */
      fontSize: {
        'xs': ['0.64rem', { lineHeight: '1.75' }],     // 10.24px
        'sm': ['0.8rem', { lineHeight: '1.5' }],       // 12.8px
        'base': ['1rem', { lineHeight: '1.5' }],      // 16px
        'lg': ['1.25rem', { lineHeight: '1.5' }],     // 20px
        'xl': ['1.5625rem', { lineHeight: '1.375' }], // 25px
        '2xl': ['1.953rem', { lineHeight: '1.375' }], // 31.25px
        '3xl': ['2.441rem', { lineHeight: '1.2' }],   // 39.06px
        '4xl': ['3.052rem', { lineHeight: '1.2' }],   // 48.83px
        '5xl': ['3.815rem', { lineHeight: '1.1' }],   // 61.04px
        '6xl': ['4.768rem', { lineHeight: '1.1' }],   // 76.29px
        // Fluid typography clamp values
        'h1': 'clamp(2.441rem, 2rem + 2.2vw, 3.815rem)',
        'h2': 'clamp(1.953rem, 1.5rem + 2vw, 3.052rem)',
        'h3': 'clamp(1.5625rem, 1.25rem + 1.5vw, 2.441rem)',
        'h4': 'clamp(1.25rem, 1rem + 1vw, 1.953rem)',
        'h5': 'clamp(1rem, 0.875rem + 0.5vw, 1.5625rem)',
        'h6': 'clamp(0.8rem, 0.75rem + 0.25vw, 1.25rem)',
        'hero': 'clamp(3.052rem, 2.5rem + 3vw, 4.768rem)',
      },

      /* ============================================
         TYPOGRAPHY - Line Heights
         ============================================ */
      lineHeight: {
        'none': '1',
        'tight': '1.2',
        'snug': '1.375',
        'normal': '1.5',
        'relaxed': '1.625',
        'loose': '1.75',
      },

      /* ============================================
         TYPOGRAPHY - Letter Spacing
         ============================================ */
      letterSpacing: {
        'tighter': '-0.05em',
        'tight': '-0.025em',
        'normal': '0',
        'wide': '0.025em',
        'wider': '0.05em',
        'widest': '0.1em',
      },

      /* ============================================
         COLORS - Complete Brand Palette
         ============================================ */
      colors: {
        // Primary - Navy Profundo (Rational)
        primary: {
          50: '#F4F5FA',
          100: '#E8EAF4',
          200: '#D0D4E8',
          300: '#B3B9D6',
          400: '#8E96BE',
          500: '#6A74A3',
          600: '#4F5785',
          700: '#363D62',
          800: '#191F3A',  // LOCKED - Brand Primary
          900: '#0D1022',
          DEFAULT: '#191F3A',
        },

        // Secondary - Borgonha (Emotional)
        secondary: {
          50: '#FDF5F5',
          100: '#FAEAEA',
          200: '#F4D2D4',
          300: '#E8A9AE',
          400: '#D67680',
          500: '#BE4652',
          600: '#9E2A35',
          700: '#81171F',  // LOCKED - Brand Secondary
          800: '#5E1118',
          900: '#3D0B10',
          DEFAULT: '#81171F',
        },

        // Accent - Ouro da Liberdade (Freedom)
        accent: {
          50: '#FEFCF3',
          100: '#FDF8E4',
          200: '#FAEFC5',
          300: '#F5E29E',
          400: '#EDD06F',
          500: '#E0B83D',  // LOCKED - Brand Accent
          600: '#C99B1F',
          700: '#A67E15',
          800: '#7D5F10',
          900: '#54400B',
          DEFAULT: '#E0B83D',
        },

        // Neutral - Cinza Azulado
        neutral: {
          50: '#F8F8FA',
          100: '#ECECF0',
          200: '#DCDCE4',
          300: '#C4C4D0',
          400: '#A5A5B5',
          500: '#85859A',
          600: '#656578',
          700: '#4A4A5A',
          800: '#32323E',
          900: '#1D1D26',
        },

        // Semantic Colors
        success: {
          light: '#E8F7EE',
          DEFAULT: '#2DA55D',
          dark: '#1A6B3A',
        },
        warning: {
          light: '#FEF7E6',
          DEFAULT: '#D4A017',
          dark: '#8B6914',
        },
        error: {
          light: '#FEF0EE',
          DEFAULT: '#D93830',
          dark: '#8E2520',
        },
        info: {
          light: '#EEF2FD',
          DEFAULT: '#3B5ED9',
          dark: '#283D8E',
        },

        // Background shortcuts
        page: '#F8F8FA',
        surface: '#FFFFFF',
        inverse: '#191F3A',
      },

      /* ============================================
         SPACING - 8pt Grid System
         ============================================ */
      spacing: {
        '0.5': '0.25rem',   // 4px
        '1': '0.5rem',      // 8px
        '1.5': '0.75rem',   // 12px
        '2': '1rem',        // 16px
        '3': '1.5rem',      // 24px
        '4': '2rem',        // 32px
        '6': '3rem',        // 48px
        '8': '4rem',        // 64px
        '12': '6rem',       // 96px
        '16': '8rem',       // 128px
        '20': '10rem',      // 160px
        '24': '12rem',      // 192px
        // Component-specific
        'button-x': '1.5rem',
        'button-y': '0.75rem',
        'button-x-sm': '1rem',
        'button-y-sm': '0.5rem',
        'button-x-lg': '2rem',
        'button-y-lg': '1rem',
        'input-x': '1rem',
        'input-y': '0.75rem',
        'card': '1.5rem',
        'card-compact': '1rem',
        'modal': '2rem',
      },

      /* ============================================
         BORDER RADIUS
         ============================================ */
      borderRadius: {
        'none': '0',
        'sm': '0.25rem',    // 4px
        'DEFAULT': '0.5rem', // 8px
        'md': '0.5rem',     // 8px
        'lg': '0.75rem',    // 12px
        'xl': '1rem',       // 16px
        '2xl': '1.5rem',    // 24px
        '3xl': '2rem',      // 32px
        'full': '9999px',
        // Component-specific
        'button': '0.5rem',
        'button-pill': '9999px',
        'input': '0.5rem',
        'card': '0.75rem',
        'card-lg': '1rem',
        'modal': '1rem',
        'avatar': '9999px',
        'badge': '0.25rem',
        'tooltip': '0.5rem',
      },

      /* ============================================
         BOX SHADOWS
         ============================================ */
      boxShadow: {
        'sm': '0 1px 2px 0 rgba(50, 50, 62, 0.05)',
        'DEFAULT': '0 4px 6px -1px rgba(50, 50, 62, 0.1), 0 2px 4px -2px rgba(50, 50, 62, 0.1)',
        'md': '0 4px 6px -1px rgba(50, 50, 62, 0.1), 0 2px 4px -2px rgba(50, 50, 62, 0.1)',
        'lg': '0 10px 15px -3px rgba(50, 50, 62, 0.1), 0 4px 6px -4px rgba(50, 50, 62, 0.1)',
        'xl': '0 20px 25px -5px rgba(50, 50, 62, 0.1), 0 8px 10px -6px rgba(50, 50, 62, 0.1)',
        '2xl': '0 25px 50px -12px rgba(50, 50, 62, 0.25)',
        'inner': 'inset 0 2px 4px 0 rgba(50, 50, 62, 0.05)',
        'none': 'none',
        // Glow effects
        'glow-primary': '0 0 20px rgba(106, 116, 163, 0.3)',
        'glow-secondary': '0 0 20px rgba(190, 70, 82, 0.3)',
        'glow-accent': '0 0 20px rgba(224, 184, 61, 0.4)',
        // Focus rings
        'focus': '0 0 0 2px #F8F8FA, 0 0 0 4px #6A74A3',
        'focus-primary': '0 0 0 2px #F8F8FA, 0 0 0 4px #191F3A',
        'focus-secondary': '0 0 0 2px #F8F8FA, 0 0 0 4px #81171F',
        'focus-accent': '0 0 0 2px #F8F8FA, 0 0 0 4px #E0B83D',
        'focus-error': '0 0 0 2px #F8F8FA, 0 0 0 4px #D93830',
      },

      /* ============================================
         BREAKPOINTS
         ============================================ */
      screens: {
        'xs': '480px',
        'sm': '640px',
        'md': '768px',
        'lg': '1024px',
        'xl': '1280px',
        '2xl': '1536px',
      },

      /* ============================================
         MAX WIDTH (Container)
         ============================================ */
      maxWidth: {
        'xs': '480px',
        'sm': '640px',
        'md': '768px',
        'lg': '1024px',
        'xl': '1280px',
        '2xl': '1536px',
      },

      /* ============================================
         Z-INDEX
         ============================================ */
      zIndex: {
        'base': '0',
        'dropdown': '100',
        'sticky': '200',
        'fixed': '300',
        'overlay': '400',
        'modal': '500',
        'popover': '600',
        'tooltip': '700',
        'toast': '800',
        'max': '9999',
      },

      /* ============================================
         ANIMATIONS - Durations
         ============================================ */
      transitionDuration: {
        'instant': '0ms',
        'fast': '100ms',
        'normal': '200ms',
        'slow': '300ms',
        'slower': '400ms',
        'deliberate': '500ms',
      },

      /* ============================================
         ANIMATIONS - Easing (Dandelion-inspired)
         ============================================ */
      transitionTimingFunction: {
        'out': 'cubic-bezier(0.16, 1, 0.3, 1)',          // Landing Seed
        'in': 'cubic-bezier(0.7, 0, 0.84, 0)',           // Departing Seed
        'in-out': 'cubic-bezier(0.45, 0, 0.55, 1)',     // Gentle Drift
        'emphasized': 'cubic-bezier(0.34, 1.56, 0.64, 1)', // Celebrated Arrival
        'spring': 'cubic-bezier(0.5, 1.8, 0.5, 0.8)',   // Organic Touch
      },

      /* ============================================
         ANIMATIONS - Keyframes
         ============================================ */
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'fade-up': {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'scale-in': {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'gentle-float': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-4px)' },
        },
        'skeleton-shimmer': {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'scroll-reveal': {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'modal-enter': {
          '0%': { opacity: '0', transform: 'scale(0.95) translateY(10px)' },
          '100%': { opacity: '1', transform: 'scale(1) translateY(0)' },
        },
        'toast-enter': {
          '0%': { opacity: '0', transform: 'translateY(16px) scale(0.95)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        'gentle-shake': {
          '0%, 100%': { transform: 'translateX(0)' },
          '25%': { transform: 'translateX(-2px)' },
          '75%': { transform: 'translateX(2px)' },
        },
      },

      /* ============================================
         ANIMATIONS - Utilities
         ============================================ */
      animation: {
        'fade-in': 'fade-in 300ms cubic-bezier(0.16, 1, 0.3, 1)',
        'fade-up': 'fade-up 300ms cubic-bezier(0.16, 1, 0.3, 1)',
        'scale-in': 'scale-in 300ms cubic-bezier(0.34, 1.56, 0.64, 1)',
        'gentle-float': 'gentle-float 3000ms cubic-bezier(0.45, 0, 0.55, 1) infinite',
        'skeleton': 'skeleton-shimmer 1800ms cubic-bezier(0.45, 0, 0.55, 1) infinite',
        'scroll-reveal': 'scroll-reveal 400ms cubic-bezier(0.16, 1, 0.3, 1)',
        'modal': 'modal-enter 300ms cubic-bezier(0.16, 1, 0.3, 1)',
        'toast': 'toast-enter 300ms cubic-bezier(0.16, 1, 0.3, 1)',
        'shake': 'gentle-shake 300ms cubic-bezier(0.16, 1, 0.3, 1)',
      },

      /* ============================================
         BACKGROUND IMAGE - Gradients
         ============================================ */
      backgroundImage: {
        'gradient-transformation': 'linear-gradient(135deg, #191F3A 0%, #81171F 100%)',
        'gradient-freedom': 'linear-gradient(135deg, #E0B83D 0%, #FAEFC5 50%, #F8F8FA 100%)',
        'gradient-sunrise': 'linear-gradient(135deg, #191F3A 0%, #81171F 40%, #E0B83D 100%)',
        'gradient-professional': 'linear-gradient(180deg, #191F3A 0%, #363D62 50%, #6A74A3 100%)',
        'gradient-warmth': 'linear-gradient(135deg, #81171F 0%, #BE4652 50%, #E8A9AE 100%)',
        'gradient-lightness': 'linear-gradient(180deg, #F8F8FA 0%, #ECECF0 100%)',
        'skeleton': 'linear-gradient(90deg, #ECECF0 0%, #F8F8FA 50%, #ECECF0 100%)',
      },

      /* ============================================
         BACKGROUND SIZE
         ============================================ */
      backgroundSize: {
        'skeleton': '200% 100%',
      },
    },
  },
  plugins: [
    // Add any plugins here
    // require('@tailwindcss/typography'),
    // require('@tailwindcss/forms'),
  ],
};
