name: forge-cta
description: Generate or regenerate CTA section with validation
version: "2.0"
category: copywriting

entry_agent: blueprint-coordinator

inputs:
  required:
    - brand_voice_document
    - avatar_profile
    - desired_action
  optional:
    - urgency_level
    - conversion_context

outputs:
  - cta-section.md

agents:
  - blueprint-coordinator
  - cta-specialist
  - brand-voice-guardian
  - avatar-advocate

pipeline:
  type: sequential
  feedback_loop:
    enabled: true
    max_rounds: 3

phases:
  - name: context
    description: Gather brand voice, avatar, and action inputs
    agent: blueprint-coordinator

  - name: creation
    description: Create CTA copy with friction reduction
    agent: cta-specialist

  - name: voice-validation
    description: Validate brand voice alignment
    agent: brand-voice-guardian
    quality_gate:
      metric: voice_alignment
      minimum: 100
      blocking: true

  - name: audience-validation
    description: Validate audience resonance
    agent: avatar-advocate
    quality_gate:
      metric: audience_resonance
      minimum: 100
      blocking: true

  - name: present
    description: Present validated CTA section
    agent: blueprint-coordinator

quality_gates:
  voice_alignment: 100
  audience_resonance: 100
