# Forge CTA Workflow Configuration
name: "forge-cta"
description: "Generate or regenerate call-to-action copy (button, supporting copy, friction reduction, urgency) with sequential brand voice and audience validation"
author: "Daniel"

# Critical variables load from config_source
config_source: "{project-root}/bmad/copy-forge/config.yaml"
copy_output_folder: "{config_source}:copy_output_folder"
validation_reports_folder: "{config_source}:validation_reports_folder"
brand_voice_folder: "{config_source}:brand_voice_folder"
avatars_folder: "{config_source}:avatars_folder"
default_avatar_profile: "{config_source}:default_avatar_profile"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated


# Module path and component files
installed_path: "{project-root}/bmad/copy-forge/workflows/forge-cta"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"

# Output configuration
cta_output_file: "{copy_output_folder}/cta-section-{{date}}.md"
validation_report_file: "{validation_reports_folder}/cta-validation-{{date}}.md"

# Workflow settings
settings:
  auto_validation: true
  max_refinement_iterations: 5
  auto_save_output: true
  generate_validation_report: true

standalone: true

web_bundle:
  name: "forge-cta"
  description: "Generate or regenerate call-to-action copy with sequential validation"
  author: "Daniel"
  template: "bmad/copy-forge/workflows/forge-cta/template.md"
  instructions: "bmad/copy-forge/workflows/forge-cta/instructions.md"
  use_advanced_elicitation: true
  web_bundle_files:
    - "bmad/copy-forge/workflows/forge-cta/instructions.md"
    - "bmad/copy-forge/workflows/forge-cta/template.md"
