# Idea Refresh Workflow
# Generate new ideas using previous research (fast refresh)
name: idea-refresh
description: "Generate new Instagram Reel ideas using previous research - fast idea generation without repeating full research"
author: "Daniel"

# Paths
installed_path: "{project-root}/bmad/viral-reels-forge/workflows/idea-refresh"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Critical variables from config
config_source: "{project-root}/bmad/viral-reels-forge/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
idea_count: "{config_source}:idea_count"
date: system-generated

# Output configuration
default_output_file: "{output_folder}/idea-refresh-{{niche_slug}}-{{date}}.md"

# Invocation control
standalone: true

# Web bundle configuration
web_bundle:
  name: "idea-refresh"
  version: "1.0.0"
  web_bundle_files:
    - "bmad/viral-reels-forge/workflows/idea-refresh/instructions.md"
    - "bmad/viral-reels-forge/workflows/idea-refresh/template.md"
    - "bmad/viral-reels-forge/workflows/idea-refresh/checklist.md"
