# Spec Generator Workflow Configuration
name: spec-generator
description: "Document workflow that compiles comprehensive technology stack specification from all Stack Advisor outputs. Produces professional, client-ready documentation with technology recommendations, architecture, rationale, and implementation guidance."
author: "Daniel"

# Paths
installed_path: "{project-root}/bmad/stack-advisor/workflows/spec-generator"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Critical variables from config
config_source: "{project-root}/bmad/stack-advisor/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Stack Advisor specific config
tech_currency_threshold: "{config_source}:tech_currency_threshold"
smb_scale_level: "{config_source}:smb_scale_level"

# Output
default_output_file: "{output_folder}/stack-advisor/tech-stack-specification-{{date}}.md"

# Invocation control
standalone: true

# Recommended inputs (load all available Stack Advisor outputs)
recommended_inputs:
  - intake_results: "{output_folder}/stack-advisor/intake-session-*.md"
  - constraint_filter: "{output_folder}/stack-advisor/constraint-filter-*.md"
  - tech_selections: "{output_folder}/stack-advisor/tech-selections-*.md"
  - architecture_blueprint: "{output_folder}/stack-advisor/architecture-blueprint-*.md"
  - comparison_matrix: "{output_folder}/stack-advisor/comparison-matrix-*.md"
  - migration_plan: "{output_folder}/stack-advisor/migration-plan-*.md"

# Web bundle configuration
web_bundle:
  name: "spec-generator"
  description: "Document workflow that compiles comprehensive technology stack specification from all Stack Advisor outputs. Produces professional, client-ready documentation with technology recommendations, architecture, rationale, and implementation guidance."
  author: "Daniel"
  instructions: "bmad/stack-advisor/workflows/spec-generator/instructions.md"
  validation: "bmad/stack-advisor/workflows/spec-generator/checklist.md"
  template: "bmad/stack-advisor/workflows/spec-generator/template.md"

  web_bundle_files:
    - "bmad/stack-advisor/workflows/spec-generator/instructions.md"
    - "bmad/stack-advisor/workflows/spec-generator/checklist.md"
    - "bmad/stack-advisor/workflows/spec-generator/template.md"
