# Generate Landing Page Workflow Configuration
name: "generate-landing-page"
description: "Generate complete, cohesive multi-section landing pages with consistent design systems"
author: "Design Forge"
version: "4.0.0"

# Critical variables from config
config_source: "{project-root}/bmad/design-forge/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Module-specific config variables
prototype_output_folder: "{config_source}:prototype_output_folder"
design_principles_path: "{config_source}:design_principles_path"
style_guide_path: "{config_source}:style_guide_path"

# Module path and component files
installed_path: "{project-root}/bmad/design-forge/workflows/generate-landing-page"
template: false
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

standalone: true

# Web bundle configuration
web_bundle:
  workflow: "bmad/design-forge/workflows/generate-landing-page/workflow.yaml"
  files:
    - "bmad/design-forge/workflows/generate-landing-page/workflow.yaml"
    - "bmad/design-forge/workflows/generate-landing-page/instructions.md"
    - "bmad/design-forge/workflows/generate-landing-page/checklist.md"
    - "bmad/design-forge/workflows/generate-landing-page/README.md"
  existing_workflows: []
