# Create Customer Personas Workflow Configuration
name: create-personas
description: "Generate research-validated customer personas based on Eugene Schwartz's 5 Levels of Customer Awareness"
author: "Persona Forge"

# Critical variables load from module config
config_source: "{project-root}/bmad/persona-forge/config.yaml"
output_folder: "{config_source}:output_folder"
persona_output_folder: "{config_source}:persona_output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
templates_path: "{config_source}:templates_path"

# System variables
date: system-generated

# Agent references (specialist agents invoked by this workflow)
persona_strategist: "{project-root}/bmad/persona-forge/agents/persona-strategist.md"
market_intelligence_analyst: "{project-root}/bmad/persona-forge/agents/market-intelligence-analyst.md"
senior_persona_specialist: "{project-root}/bmad/persona-forge/agents/senior-persona-specialist.md"

# Template references
persona_template: "{templates_path}/persona-document.md"

# Module path and component files
installed_path: "{project-root}/bmad/persona-forge/workflows/create-personas"
template: false # This is an interactive workflow with agent orchestration
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Output configuration
default_output_file: "{persona_output_folder}/persona-{{persona_name_slug}}-{{date}}.md"
qualification_output_file: "{persona_output_folder}/qualification-questions-{{date}}.md"

# Workflow state management
max_correction_cycles: 3
current_cycle: 0

# Multi-persona state tracking (V2)
persona_count: null # Set by user in Step 2b (1-3)
persona_differentiators: null # Set by user if persona_count > 1
persona_labels: [] # Working names/labels for each persona

standalone: true

# Web bundle configuration
web_bundle:
  name: "create-personas"
  description: "Generate research-validated customer personas based on Eugene Schwartz's 5 Levels of Customer Awareness"
  author: "Persona Forge"
  instructions: "bmad/persona-forge/workflows/create-personas/instructions.md"
  web_bundle_files:
    - bmad/persona-forge/workflows/create-personas/instructions.md
    - bmad/persona-forge/workflows/create-personas/checklist.md
    - bmad/persona-forge/agents/persona-strategist.md
    - bmad/persona-forge/agents/market-intelligence-analyst.md
    - bmad/persona-forge/agents/senior-persona-specialist.md
    - bmad/persona-forge/templates/persona-document.md
    - bmad/persona-forge/templates/qualification-questions.md
